import rosaProfilePic from "./assets/profile_pic.png";
import rosaCover from "./assets/Cover.png";

export const people = [
  {
    rosaMaria: {
      name: "Rosa María Álvarez",
      role: "Asesora Inmobiliaria |❤️✈️| Estudiante de coaching",
      description:
        "Me dedico a brindar un servicio personalizado y de calidad, adaptado a la necesidad de cadaHeaderProps",
      links: {
        whatsapp: "https://wa.me/message/63G3GQCG742WM1",
        tiktok: "https://www.tiktok.com/@rosamariaalvarezsalas",
        instagram: "https://www.instagram.com/rosa_alvarezs",
        facebook: "https://www.facebook.com/rosamariarealtor",
        linkedin: "https://www.linkedin.com/in/rosa-maria-alvarez-salas-/",
        youtube: "https://www.youtube.com/@rosamariaalvarezsalas",
      },
      images: {
        profile: rosaProfilePic,
        cover: rosaCover,
      },
      cta: {
        vcf: "src/assets/rosamaria.vcf",
        linkTo: "https://wa.link/2q2tzs",
        textCTA: "Ver Más",
      },
      properties: [
        {
          url: "https://www.remax.pe/web/search/property/propiedad-casa-en-venta-la-molina-lima-lima-1096139/",
          image: "src/assets/rma/casa_la_molina.jpg",
          title: "CASA URBANA EN VENTA",
          priceSol: "S/. 1'757,800.00",
          priceUsd: "USD 470,000.00",
          location: "Lima, Lima, La Molina",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-terreno-en-alquiler-chorrillos-lima-lima-1096089/",
          image: "src/assets/rma/terreno_en_alquiler.jpg",
          title: "TERRENO COMERCIAL EN ALQUILER",
          priceSol: "S/. 11,220.00",
          priceUsd: "USD 3,000.00",
          location: "Lima, Lima, Chorrillos",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-venta-miraflores-lima-lima-1092314/",
          image: "src/assets/rma/depa_duplex_venta.jpg",
          title: "DEPARTAMENTO DUPLEX EN VENTA",
          priceSol: "S/. 935,000.00",
          priceUsd: "USD 250,000.00",
          location: "Lima, Lima, Miraflores",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-alquiler-san-isidro-lima-lima-1092222/",
          image: "src/assets/rma/depa_flat_alquiler.jpg",
          title: "DEPARTAMENTO FLAT EN ALQUILER",
          priceSol: "S/. 4,862.00",
          priceUsd: "USD 1,300.00",
          location: "Lima, Lima, San Isidro",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-venta-miraflores-lima-lima-1089713/",
          image: "src/assets/rma/depa_flat_venta.jpg",
          title: "DEPARTAMENTO FLAT EN VENTA",
          priceSol: "S/. 1'795,200.00",
          priceUsd: "USD 480,000.00",
          location: "Lima, Lima, Miraflores",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-venta-surquillo-lima-lima-1084225/",
          image: "src/assets/rma/depa_flat_venta_surquillo.jpg",
          title: "DEPARTAMENTO FLAT EN VENTA",
          priceSol: "S/. 299,200.00",
          priceUsd: "USD 80,000.00",
          location: "Lima, Lima, Surquillo",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-alquiler-san-isidro-lima-lima-1082111/",
          image: "src/assets/rma/depa_flat_alquiler_san_isidro.jpg",
          title: "DEPARTAMENTO FLAT EN ALQUILER",
          priceSol: "S/. 4,675.00",
          priceUsd: "USD 1,250.00",
          location: "Lima, Lima, San Isidro",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-terreno-en-alquiler-chorrillos-lima-lima-1082081/",
          image: "src/assets/rma/terreno_alquiler_chorrillos.jpg",
          title: "TERRENO COMERCIAL EN ALQUILER",
          priceSol: "S/. 44,880.00",
          priceUsd: "USD 12,000.00",
          location: "Lima, Lima, Chorrillos",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-venta-santiago-de-surco-lima-lima-1082047/",
          image: "src/assets/rma/depa_flat_venta_surco.jpg",
          title: "DEPARTAMENTO FLAT EN VENTA",
          priceSol: "S/. 1'365,100.00",
          priceUsd: "USD 365,000.00",
          location: "Lima, Lima, Santiago de Surco",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-terreno-en-venta-carabayllo-lima-lima-1080254/",
          image: "src/assets/rma/terreno_venta_Carabayllo.jpeg",
          title: "TERRENO COMERCIAL EN VENTA",
          priceSol: "S/. 224,400.00",
          priceUsd: "USD 60,000.00",
          location: "Lima, Lima, Carabayllo",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-terreno-en-alquiler-chorrillos-lima-lima-1080229/",
          image: "src/assets/rma/terreno_industrial_alquiler_chorrillos.jpg",
          title: "TERRENO INDUSTRIAL EN ALQUILER",
          priceSol: "S/. 164,560.00",
          priceUsd: "USD 44,000.00",
          location: "Lima, Lima, Chorrillos",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-venta-santiago-de-surco-lima-lima-1079023/",
          image: "src/assets/rma/depa_flat_venta_surco2.jpg",
          title: "DEPARTAMENTO FLAT EN VENTA",
          priceSol: "S/. 243,100.00",
          priceUsd: "USD 65,000.00",
          location: "Lima, Lima, Santiago de Surco",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-venta-miraflores-lima-lima-1078116/",
          image: "src/assets/rma/depa_flat_venta_miraflores.jpg",
          title: "DEPARTAMENTO FLAT EN VENTA",
          priceSol: "S/. 935,000.00",
          priceUsd: "USD 250,000.00",
          location: "Lima, Lima, Miraflores",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-venta-lince-lima-lima-1077439/",
          image: "src/assets/rma/depa_flat_venta_Lince.jpg",
          title: "DEPARTAMENTO FLAT EN VENTA",
          priceSol: "S/. 822,800.00",
          priceUsd: "USD 220,000.00",
          location: "Lima, Lima, Lince",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-venta-santiago-de-surco-lima-lima-1076943/",
          image: "src/assets/rma/depa_flat_venta_surco3.jpg",
          title: "DEPARTAMENTO FLAT EN VENTA",
          priceSol: "S/. 411,400.00",
          priceUsd: "USD 110,000.00",
          location: "Lima, Lima, Santiago de Surco",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-terreno-en-venta-aguas-verdes-zarumilla-tumbes-1076042/",
          image: "src/assets/rma/terreno_agricula_venta_tumbes.jpg",
          title: "TERRENO AGRÍCOLA EN VENTA",
          priceSol: "S/. 6'941,701.00",
          priceUsd: "USD 1'856,070.00",
          location: "Tumbes, Zarumilla, Aguas Verdes",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-casa-en-venta-santiago-de-surco-lima-lima-1075167/",
          image: "src/assets/rma/casa_urbana_venta_surco.jpg",
          title: "CASA URBANA EN VENTA",
          priceSol: "S/. 1'492,260.00",
          priceUsd: "USD 399,000.00",
          location: "Lima, Lima, Santiago de Surco",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-terreno-en-venta-santa-rosa-lima-lima-1069454/",
          image: "src/assets/rma/terreno_comercial_venta_santa_rosa.jpg",
          title: "TERRENO COMERCIAL EN VENTA",
          priceSol: "S/. 306,680.00",
          priceUsd: "USD 82,000.00",
          location: "Lima, Lima, Santa Rosa",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-venta-santiago-de-surco-lima-lima-1065659/",
          image:
            "https://sfo3.digitaloceanspaces.com/media-remax-peru/media/public/photos/propertys/1065659/cover_1065659.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&X-Amz-Credential=PVSQWTTYSF24OLDHUMMG%2F20240611%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Date=20240611T060509Z&X-Amz-Signature=a58a0c360f85376ddb8490caa74788a96e22e6138fc0008b023edcc6a8e0a75b",
          title: "DEPARTAMENTO FLAT EN VENTA",
          priceSol: "S/. 1'166,880.00",
          priceUsd: "USD 312,000.00",
          location: "Lima, Lima, Santiago de Surco",
        },
        {
          url: "https://www.remax.pe/web/search/property/propiedad-departamento-en-venta-miraflores-lima-lima-1056803/",
          image: "src/assets/rma/depa_flat_venta_miraflores_2.jpg",
          title: "DEPARTAMENTO FLAT EN VENTA",
          priceSol: "S/. 4'114,000.00",
          priceUsd: "USD 1'100,000.00",
          location: "Lima, Lima, Miraflores",
        },
      ],
    },
  },
];
